package com.nyx.nyx;

enum TokenIdentifier {
	// LITERALS
	INT, STRING, IDENTIFIER

	// KEYWORDS
	VAR, CLASS, THIS, FUNCTION, IF, ELSE, WHILE, TRUE, FALSE, AND, OR, NULL,
	OUTPUT, RETURN, SUPER, FOR, EOF

	// SINGLE CHAR TOKENS
	SEMICOLON, DOT, COMMA, PLUS, MINUS, FORWARD_SLASH, LEFT_BRACKET, RIGHT_BRACKET,
	LEFT_BRACE, RIGHT_BRACE, ASTERISK,

	// 1+ CHAR TOKENS
	NOT, NOT_EQUAL, EQUAL, EQUAL_TO, GREATER, GREATER_THAN_OR_EQUAL, LESS, LESS_THAN_OR_EQUAL

}